//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 7/12/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject


// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawOval;
+ (void)drawBurgerMenu;
+ (void)drawNotification;
+ (void)drawRectPro;
+ (void)drawNoteView;
+ (void)drawCard;
+ (void) drawProfileViewExtensive;

+ (UIColor*)color;

@end
